### ISSUE TITLE
An unexpected error occurred. FileSystemException: Cannot open file, path = 

### ISSUE THREAD

**Issue by GisAdminLKSPN** [Esri/arcgis-maps-sdk-flutter-samples#12]
Hello,

after "dart run arcgis_maps install" i become the error "An unexpected error occurred. FileSystemException: Cannot open file, path = '/C:/src/esri/arcgis_maps_package/install.json' (OS Error: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. , errno = 123)"

looks like "/C:" is wrong

**Comment by jenmerritt** [comment]
Hi @GisAdminLKSPN !

Thank you for your feedback.

For the initial phase of the beta, we are only supporting macOS as a development host, and so that is why the installation has failed with the Windows path as you describe. 

It should be technically feasible to use Windows as the development host and target Android for deployment -- we just have to devote the resources to making it work (and that includes the Samples workflows). We chose macOS initially with it being required for iOS development, and with the ArcGIS Maps SDK targeting both Android and iOS. 

All that said - the fact that you are looking to use Windows as the development host is useful feedback to us!

Out of interest, do you plan to target iOS as well, or Android only?

Please feel free to respond here, or use the [Early Adopter forum](https://earlyadopter.esri.com/key/flutter) if you wish to discuss further.

Thanks again for your feedback!

**Comment by GisAdminLKSPN** [comment]
we are targeting all 3 platforms ios, android and web.

thx

**Comment by jenmerritt** [comment]
For deployment targets we are initially supporting iOS and Android.
Deploying on Windows and macOS is on our longer-term roadmap, and your feedback helps us prioritize our future efforts.

As for web, we don't intend to support web as a target with ArcGIS Maps SDK for Flutter as it is not suitable for our Native SDKs - our ArcGIS Maps SDK for JavaScript is better placed for web projects.

Your feedback is useful, so thanks again!

**Comment by GisAdminLKSPN** [comment]
Ok thanks for the answer. but with Flutter you can very quickly
create an exe for windows or a web app with just one click and you don't need any additional knowledge about a java-script sdk.

and that is ultimately a huge advantage!

But time will tell.

**Comment by jenmerritt** [comment]
Closing this issue as answered. We will be releasing a Beta 2 release of ArcGIS Maps SDK for Flutter in just a few weeks in August, and we will be officially supporting Windows as a development host. Our position on support for Desktop and web deployment remain as per my above response. 

Don't hesitate to reopen this issue or get in touch via our [Early Adopter](https://earlyadopter.esri.com/) forum if you have any other questions. Thank you!
