### ISSUE TITLE
attributes

### ISSUE THREAD

**Issue by amr-muhammad-anwar** [Esri/arcgis-maps-sdk-flutter-samples#142]
when get attributes from features then print list length 
--> length printed successfully but then print [W] 12:03:06.292248 removeInstance: expected Feature 5315918080 not found 
then app crashed 

<img width="619" alt="Screenshot 2024-09-08 at 12 04 10 PM" src="https://github.com/user-attachments/assets/73a59124-b95c-4c51-af5e-f5b18184b700">
<img width="659" alt="Screenshot 2024-09-08 at 12 04 38 PM" src="https://github.com/user-attachments/assets/72e6607e-c8c7-4988-8e2f-62109deda67f">

**Comment by amr-muhammad-anwar** [comment]
@PaulAllanSturm

**Comment by amr-muhammad-anwar** [comment]
happened when features().length has high number @PaulAllanSturm

**Comment by jenmerritt** [comment]
Hi @amr-muhammad-anwar - is this a bug in a sample or is this in an app you're building? We try to focus issues in this repo on samples specifically, and manage bugs in the API itself or other API related feedback within our [Early Adopter forum](https://earlyadopter.esri.com/flutter). 

I'm assuming since you are playing around with the API that you are a member of our Early Adopter program? If so, please could you submit this issue via the user forums at https://earlyadopter.esri.com/flutter? If you're able to provide any other info such as the service you're using that would be great and we can assist there.

Thank you!
